spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audify_db
    username: postgres
    password: 123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

media:
  image:
    supported-extensions: "png,jpeg,jpg"
  audio:
    supported-extensions: "mp3"

elasticsearch:
  url: localhost:9200

logging:
  level:
    org:
      springframework:
        web: DEBUG
    tracer: TRACE